repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: sort-simple-yaml
        files: ^config/simple/
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.16
    hooks:
      - id: uv-lock

  - repo: https://github.com/owenlamont/uv-secure
    rev: 0.15.1
    hooks:
      - id: uv-secure

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff-format
        name: ruff-format (commit)
        stages: [commit]
      - id: ruff
        name: ruff check --fix (commit)
        args: ["--fix"]
        stages: [commit]
      - id: ruff
        name: ruff check (push)
        stages: [push]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 42.39.6
    hooks:
      - id: renovate-config-validator
        args: [--strict]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture
