# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: optimes
repo_url: https://github.com/ramirorcr/optimes
site_url: https://ramirorcr.github.io/optimes
site_description: Python framework for optimizing multi-energy systems
site_author: Ramiro Criach
edit_uri: edit/main/docs/
repo_name: ramirorcr/optimes
copyright: Maintained by <a href="https://ramirorcr.com">ramirorcr</a>.

nav:
  - Home:
      - Welcome to OptimMES: index.md
  - Getting Started:
      - Installation: getting_started/installation.md
      - Minimal Example: getting_started/minimal_example.md
  - Concepts:
      - Assets: concepts/assets.md
      - Portfolio: concepts/portfolio.md
      - Energy System: concepts/energy_system.md
      - Optimizer: concepts/optimizer.md
  - API Reference:
      - Overview: api/main.md
      - Energy System: api/energy_system.md
      - Optimization: api/optimization.md
      - Solvers: api/solvers.md
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ramirorcr/optimes
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/optimes

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/optimes"]
  - exclude:
      glob:
        - __pycache__/*
markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition

  # Python Markdown Extensions
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
