# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Odys
repo_url: https://github.com/ramirocrc/odys
site_url: https://ramirocrc.github.io/odys
site_description: Python framework for optimizing multi-energy systems
site_author: Ramiro Criach
edit_uri: edit/main/docs/
repo_name: ramirocrc/odys
copyright: Maintained by <a href="https://ramirocrc.com">ramirocrc</a>.

nav:
  - Home: index.md
  - User Guide:
      - Models:
          - PowerGenerator: user_guide/power_generator.md
          - Battery: user_guide/battery.md
          - Load: user_guide/load.md
          - Market: user_guide/market.md
          - AssetPortfolio: user_guide/asset_portfolio.md
          - Scenario: user_guide/scenario.md
          - StochasticScenario: user_guide/stochastic_scenario.md
          - EnergySystem: user_guide/energy_system.md
      - Optimization: user_guide/optimization.md
      - Stochastic Optimization: user_guide/stochastic.md
      - Multi-stage Optimization: user_guide/multi_stage.md
  - Examples:
      - Overview: examples/index.md
      - Basic Dispatch: examples/basic_dispatch.md
      - Stochastic Scenarios: examples/stochastic.md
      - Stochastic Without Batteries: examples/stochastic_no_batteries.md
      - Markets: examples/markets.md
      - Markets + Stochastic: examples/markets_stochastic.md
  - API Reference:
      - Overview: api/index.md
      - Energy System: api/energy_system.md
      - Optimization: api/optimization.md
      - Math Model: api/math_model.md
      - Solvers: api/solvers.md
  - Contributing: contributing.md

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ramirocrc/odys
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/odys

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/odys"]
  - exclude:
      glob:
        - __pycache__/*
markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition

  # Python Markdown Extensions
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
