[project]
name = "optimes"
version = "0.0.1"
description = "Python framework for optimizing multi-energy systems"
authors = [{ name = "Ramiro Criach", email = "ramirocriach@gmail.com" }]
readme = "README.md"
keywords = ['python']
requires-python = ">=3.10,<4.0"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "highspy>=1.11.0",
    "pydantic>=2.11.7",
    "pyomo>=6.9.2",
    "rich>=14.0.0",
]

[project.urls]
Homepage = "https://ramirorcr.github.io/optimes/"
Repository = "https://github.com/ramirorcr/optimes"
Documentation = "https://ramirorcr.github.io/optimes/"

[dependency-groups]
dev = [
    "deptry>=0.23.0",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
    "mkdocstrings-python>=1.16.12",
    "nox>=2025.5.1",
    "pre-commit>=4.2.0",
    "pyright>=1.1.402",
    "pytest>=8.4.0",
    "pytest-cov>=6.2.1",
    "ruff>=0.11.13",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/optimes"]


[tool.pytest.ini_options]
testpaths = ["tests"]


[tool.ruff]
exclude = [
    # "src/optimes/math_model/"
]
line-length = 120
target-version = "py313"

[tool.ruff.lint]

select = [
     "ALL"
]

ignore = [
    "D", # Docstring style (pydocstyle)
    "G004", # Logging statement uses f-string
    # "ANN",
    # "ARG"
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = [
    "INP001",# Checks for packages that are missing an __init__.py
    "S101", # Use of 'assert' detected
]

[tool.ruff.format]
preview = true


[tool.pyright]
typeCheckingMode = "standard"
ignore = [
    "src/optimes/math_model/energy_model.py"
]

[tool.deptry.per_rule_ignores]
DEP002 = [ "highspy"]
[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["src"]
