name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup_environment

      - name: Cache virtual environment
        uses: actions/cache/save@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}

  check-quality:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Setup tools
        uses: ./.github/actions/setup_just_and_uv

      - name: Restore virtual environment
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}

      - name: Run checks
        run: just check

  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Setup tools
        uses: ./.github/actions/setup_just_and_uv

      - name: Restore virtual environment
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}

      - name: Run tests
        run: just test

  test_versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12", "3.14"] # Test only LTS versions
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup tools
        uses: ./.github/actions/setup_just_and_uv

      - name: Cache dependencies for Python ${{ matrix.python-version }}
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}

      - name: Install dependencies with dev group
        run: uv sync --python ${{ matrix.python-version }} --group dev

      - name: Run tests
        run: uv run --locked python -m pytest tests/ -n auto

  check-docs:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Setup tools
        uses: ./.github/actions/setup_just_and_uv

      - name: Restore virtual environment
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}

      - name: Check if documentation can be built
        run: just docs-test
