name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - uses: actions/cache@v4
        with:
          path: ~/.cache/prek
          key: prek-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Setup environment
        uses: ./.github/actions/setup_environment

      - name: Run checks
        run: just check

      - name: Run tests
        run: just test

      - name: Check if documentation can be built
        run: just docs-test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      python-versions: ${{ steps.extract-versions.outputs.python-versions }}
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Extract Python versions from pyproject.toml
        id: extract-versions
        run: |
          python_versions=$(python -c "
          import tomllib
          from pathlib import Path
          pyp = tomllib.loads(Path('pyproject.toml').read_text())
          versions = [pv.rsplit(' ')[-1] for pv in pyp['project']['classifiers'] if pv.startswith('Programming Language :: Python ::')]
          print(str(versions).replace(\"'\", '\"'))
          ")
          echo "python-versions=$python_versions" >> $GITHUB_OUTPUT

  integration_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.get-python-versions.outputs.python-versions) }}
        resolution: ["highest", "lowest-direct"]
      fail-fast: false
    needs: get-python-versions
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup tools
        uses: ./.github/actions/setup_just_and_uv

      - name: Install dependencies
        run: uv sync --python ${{ matrix.python-version }} --all-groups --resolution ${{ matrix.resolution }}

      - name: Run tests
        run: uv run python -m pytest tests/integration -n auto
